---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-dns
spec:
  acme:
    dns01:
      providers:
        -
          name: dns
          route53:
            accessKeyID: XXXXXXXXXXXXX
            region: us-west-2
            secretAccessKeySecretRef:
              key: secret-access-key
              name: acme-route53
    email: shkbha.666@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production-dns
    server: "https:acme-v02.api.letsencryp.org/directory"
