apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: bot-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: presentation-gitlab-k8s
    # Reference to upper's `metadata.namespace`
    namespace: presentation-gitlab-k8s
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
